### ISSUE TITLE
As a <student>, I want <to edit the visualization type I’m working on> so that <I can make changes, fix something, or explore>.

### ISSUE THREAD

**Issue by bherr2** [cns-iu/make-a-vis#107]
Ensure the IVC student can edit the visualization by:

- [x] having a button for EDIT (using icon) in the tabs area where the created visualizations appear that changes state on hover from outline to solid style and on click opens the Make Visuallization panel while pushing the visualization area to the right (NOTE: this should be animated)
- [x] having the first section of the Make Visualization panel be open, with it and the other sections, having the previous selections and the DONE/VISUALIZE buttons active
- [x] having the user complete the same essential steps as needed that are part of the initial making process *
- [x] having changes reflected in the visualization and legend as they step through updates

**Comment by GagsdName** [comment]
Animation of selection panel is pending.
