### ISSUE TITLE
As a <student>, I want <to collapse the Graphic Variable symbols> so that <I can more easily work with dragging and dropping of data variables on the cards>.

### ISSUE THREAD

**Issue by bherr2** [cns-iu/make-a-vis#112]
Ensure the IVC student can collapse Graphic Variable Nodes and Edges by:

- [x] showing the established collapse icon
- [x] collapsing or expanding the section affected when the user clicks on the icon

**Comment by GagsdName** [comment]
This is enabled via expansion panels for graphic-symbols corresponding to the graphic-variables the user is editing.
