### ISSUE TITLE
As a <teacher>, I want <to have the UI look like Leonard's mockup>, so that <the UI will be awesome>.

### ISSUE THREAD

**Issue by bherr2** [cns-iu/make-a-vis#124]
Update the UI to mach Leonard's mockup.

You can see the mockup here:
https://drive.google.com/file/d/1GB8jzbRXXEdn5_ROnZtDi0c9vzmcsQ9g/view?usp=sharing

Addendum 1:
[https://app.zenhub.com/files/142600324/47a01767-e712-475b-afd6-dd4b44d4339b/download](https://app.zenhub.com/files/142600324/47a01767-e712-475b-afd6-dd4b44d4339b/download)

Spec Doc:
https://drive.google.com/file/d/1vKAb747QORWeF4K5kW4FxQ_u-kQWeQgp/view?usp=sharing

**Comment by bherr2** [comment]
@lecross what should the height of the toolbar be set to now?

**Comment by bherr2** [comment]
The top navigation nav bar

**Comment by lecross** [comment]
The top navigation bar with the hamburger is 40px tall in the spec. Anything close to that works. I would not go less. If you want to move to 48px, which believe is the default row height, I’m good with that.

Leonard Cross




Senior Interaction Designer
School of Informatics, Computing, and Engineering
700 N. Woodlawn Ave, #4014
lecross@iu.edu<mailto:lecross@iu.edu>
812.856.5293


On Dec 6, 2018, at 10:50 AM, Bruce W. Herr II <notifications@github.com<mailto:notifications@github.com>> wrote:


The top navigation nav bar

**Comment by bherr2** [comment]
Ok, let's go with fixed height, 48px. When you say spec, is there another document I'm missing?

**Comment by bherr2** [comment]
After talking with Leonard, we decided on a 40px height for the toolbar. We also decided that for local sizing to use rem units (16px per rem), global screen-based sizing uses vw/vh, and how to structure components so they will be easy to theme. I'll try write up a short doc and report back here.

**Comment by lecross** [comment]
NOTES:

This revised design introduces a few changes:

1. Not captured in the original mocks, observe the Journals table. Note there is no collapse top left. If there is no child there is no need for the chevron and the table should take the full width.
2. The legend has a new card that surrounds and defines the interior elements as being nodes or edges. Katy is reviewing label names. This adds clarity and relies on existing card styling. The interior cards for the various variables have had changes made to spacing. I tightened things up to compensate for some of the space lost with the addition of the surrounding card and the about dropdown. These will use the interior 10px padding for the card interior, which is what they should have used anyways.
3. Naming is in flux on the GV section mostly. I’ll update as that is clarified.

If you have questions, please reach-out.

**Comment by bherr2** [comment]
@lecross can you link to the revised design?

**Comment by bherr2** [comment]
Attached addendum 1 from Leonard

[https://app.zenhub.com/files/142600324/47a01767-e712-475b-afd6-dd4b44d4339b/download](https://app.zenhub.com/files/142600324/47a01767-e712-475b-afd6-dd4b44d4339b/download)

**Comment by bherr2** [comment]
Attached spec doc from Leonard

https://drive.google.com/file/d/1vKAb747QORWeF4K5kW4FxQ_u-kQWeQgp/view?usp=sharing
