### ISSUE TITLE
Edge - Save Project - Requires multiple clicks and opening/closing of side menu.

### ISSUE THREAD

**Issue by axdanbol** [cns-iu/make-a-vis#215]
Sporadic behavior when attempting to save a project.
- Multiple clicks is sometimes required.
- Closing and reopening of the side bar is sometimes required.
- No name or file type is set on the downloaded file.

**Comment by axdanbol** [comment]
After further evaluation I've concluded that this in not a bug. Its just edge that is very slow!

**Comment by bherr2** [comment]
We should open an issue to make this more transparent to the user, so that they know its processing. Maybe gray out the button and have a spinner at least.
