### ISSUE TITLE
Cannot load .yml project file through hamburger icon/sidebar (FIX NEEDED for Visual Analytics 2019 course)

### ISSUE THREAD

**Issue by santoshd97** [cns-iu/make-a-vis#265]
Students in IVC 2019 course have reported the following issue in MAV:
If you try to load .yml project file through the hamburger icon/sidebar -> open project, then the file does not load. However, it loads if you select + button next to data on the home page.

**Comment by bherr2** [comment]
@gurjaspalbedi will look at this tody. Thanks for reporting.

**Comment by gurjaspalbedi** [comment]
@bherr2 : I will check it!

**Comment by santoshd97** [comment]
This is the .yml file for assignment 1 in Visual Analytics

[mav-drbean-scattergraph-aisha-start.yml.zip](https://github.com/cns-iu/make-a-vis/files/3790814/mav-drbean-scattergraph-aisha-start.yml.zip)

**Comment by gurjaspalbedi** [comment]
@santoshd97 thanks

**Comment by bherr2** [comment]
Fixed and on production now.
