### ISSUE TITLE
Log State Changes

### ISSUE THREAD

**Issue by gurjaspalbedi** [cns-iu/make-a-vis#65]
Log all state changes from ngrx. Explore what's possible with the API, a likely good solution is creating a decorator to automatically log action functions.

**Comment by bherr2** [comment]
@gurjaspalbedi I updated the description, let me know if this doesn't jive with what you thought you needed to do.

**Comment by bherr2** [comment]
Moving this back to backlog as it is not truly done done

**Comment by bherr2** [comment]
I think @Effects are fine (and good), but the nano-sql side is lacking/brittle. Further, I just want to be sure we are fully capturing the user activity and I'm not convinced that's done yet.

We can review this specific line of work early next week.
