### ISSUE TITLE
Temporal Bar Graph Vis

### ISSUE THREAD

**Issue by bherr2** [cns-iu/make-a-vis#70]
Create the Temporal Bar Graph Vis as an @ngx-dino component and wrapped with DVL.

**Comment by bherr2** [comment]
This was not able to be finished in Sprint 1. It will be moved back to the next Sprint.

**Comment by bherr2** [comment]
Just a reminder to use the attached file for the mapping to use for TBG on NSF files (there is no spec for TBG on ISI, so we'll not do that one for now).

https://app.zenhub.com/files/142600324/e9e557b7-8086-4eb5-a4cc-ce6d28a6bcbb/download

**Comment by katyb** [comment]
Correct.
Please do TBG for highly funded AI NSF projects—see data in BOX, detailed workflow + result in doc file you reviewed.
k


--
Katy Borner
Victor H. Yngve Distinguished Professor of Engineering and Information Science
Director, CI for Network Science Center, http://cns.iu.edu
Curator, Mapping Science exhibit, http://scimaps.org

ISE and ILS, School of Informatics, Computing, and Engineering, Indiana University
Luddy Hall 4018, 700 N. Woodlawn Ave, Bloomington, IN 47408, USA
Phone: (812) 855-3256  Fax: -6166
